### ISSUE TITLE
Error during backup

### ISSUE THREAD

**Issue by thinhluu** [godaddy/kibana4-backup#17]
kibana4-backup Starting kibana4 backup +187ms
  kibana4-backup Repo detected, skipping clone +3ms
  kibana4-backup Checking out master and getting latest from kibana4 +0ms
  kibana4-backup Creating directories if they do not already exist +561ms
  kibana4-backup Creating READMEs in backup and deploy directories +2ms
  kibana4-backup Restoring everything in backup to .kibana index +200ms
  kibana4-backup Looking in deploy directory for changes +1ms
  kibana4-backup Starting backup +1ms
  kibana4-backup Saving .kibana index data to temp directory +1ms

Error: <!DOCTYPE html><html><head><title></title><link rel="stylesheet" href="/styles/main.css"></head><body><h1>Not Found</h1><h2></h2><pre></pre></body></html>
    at Request.requestResonse [as _callback] (/usr/local/lib/node_modules/kibana4-backup/node_modules/elasticdump/lib/transports/elasticsearch.js:89:27)
    at Request.self.callback (/usr/local/lib/node_modules/kibana4-backup/node_modules/request/request.js:198:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/kibana4-backup/node_modules/request/request.js:1063:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/kibana4-backup/node_modules/request/request.js:1009:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by gshively11** [comment]
Are you able to get a valid response from the url you used in the `--elasticsearch-url` argument?  Without digging in, it looks like kibana4-backup attempted to read the .kibana index via the url provided but ran into an unexpected response.

Can you paste the full command you ran, and also paste the output when running the command with debugging enabled (`DEBUG=kibana4-backup restofcommandgoeshere`, assuming you're on linux)

**Comment by thinhluu** [comment]
Hi Grant,

Thank you for reaching out so quickly. I got a wrong port from the ES team
which was the cause of the error. After I changed it to the correct port,
everything is working correctly.

Do you have any instruction to back up Kibana 3 dashboard?

Thanks again,
Thinh

**Comment by gshively11** [comment]
Assuming you're using the default Kibana 3 configuration, you should be able to use the same arguments (except the git repo, which should be different) and add "-i kibana-int" (no quotes, I can't do backticks on my phone to get the right formatting)
